# The role postgres is copy/pasted from bahmni-playbooks.
- hosts: bahmni-mart-db:bahmni-mart-db-slave
  become: yes
  roles:
    - { role: postgres, postgres_user: analytics }

- hosts: bahmni-mart
  become: yes
  roles:
    - { role: bahmni-mart }
    - { role: gnupg }

- hosts: bahmni-mart-scdf
  become: yes
  roles:
    - { role: bahmni-mart-scdf }

- hosts: metabase-db:metabase-db-slave
  become: yes
  roles:
    - { role: postgres, postgres_user: metabase }

- hosts: metabase
  become: yes
  roles:
    - { role:  metabase }