
- name: Check if bahmni-mart rpm needs an update
  yum:
    list: bahmni-mart
  register: installed_bahmni_mart
  ignore_errors: true

- name: Uninstall bahmni-mart rpm
  yum: name="bahmni-mart" state=absent
  when: installed_bahmni_mart.results|length != 0 and installed_bahmni_mart.results[0].version != "{{ bahmni_mart_version }}"

- name: Install bahmni-mart using URL
  yum: name="{{ bahmni_mart_url }}" state=present

- name: Set bahmni_mart_scdf_schema_name
  set_fact:
    bahmni_mart_scdf_schema_name: 'public'
  when: groups['bahmni-mart-scdf'] is not defined or groups['bahmni-mart-scdf']|length == 0

- name: Copy bahmni-mart config
  template:
    src=application.properties.j2
    dest=/opt/bahmni-mart/properties/application.properties
    mode=644
    owner={{ bahmni_user }}
    group={{ bahmni_group }}

- name: Create bahmni-mart DB
  postgresql_db:
    name: "{{ analytics_db_name }}"
    owner: "{{ analytics_db_user }}"
    
- name: Create backup directory
  file:
    path: /data/analytics
    mode: 0666
    owner: "{{ bahmni_user }}"
    group: "{{ bahmni_group }}"
    state: directory