
- name: Install Liquibase
  yum:
    name: liquibase
    state: present

- name: Get postgresSql jar
  get_url:
    url: "https://jdbc.postgresql.org/download/postgresql-42.2.2.jar"
    dest: "{{ postgresql_jar_location }}"
    mode: 644
    owner: "{{ bahmni_user }}"
    group: "{{ bahmni_group }}"

- name: Run Liquibase migration
  command: "liquibase --driver='org.postgresql.Driver' --classpath='{{ postgresql_jar_location }}/{{ postgresql_jar_name }}' --changeLogFile='{{ liquibase_changelog_path }}' --defaultSchemaName='public' --url=jdbc:postgresql://{{ analytics_db_server }}:{{ analytics_db_port }}/{{ analytics_db_name }} --username={{ analytics_db_user }} --password={{ analytics_db_password }} update"

- name: Set analytics_db_server variable
  set_fact:
    analytics_db_server: "{{ default_docker_ip }}"
  when: analytics_db_server == 'localhost' or analytics_db_server == '127.0.0.1'

- name: Set openmrs_db_server variable
  set_fact:
    openmrs_db_server: "{{ default_docker_ip }}"
  when: openmrs_db_server == 'localhost' or openmrs_db_server == '127.0.0.1'

- name: Install and start docker
  include_role:
    name: docker

- name: Copy docker-compose file for bahmni-mart-scdf
  template:
    src: docker-compose.yml.j2
    dest: "{{ bahmni_mart_scdf_docker_compose_location }}"
    mode: 644
    owner: "{{ bahmni_user }}"
    group: "{{ bahmni_group }}"

- name: Copy bahmni-mart properties
  template:
    src: application.properties.j2
    dest: /opt/bahmni-mart/properties/application-docker.properties
    mode: 644
    owner: "{{ bahmni_user }}"
    group: "{{ bahmni_group }}"

- name: Update postgres config
  include_role:
    name: pg_hba
  vars:
    app_server_group: bahmni_mart_scdf
    db_user: "{{ analytics_db_user }}"
    db_name: "{{ analytics_db_name }}"
    host: "{{ analytics_db_server }}"
    postgres_version: 9.2

- name: Create bahmni-mart-scdf docker conatainer
  command: docker-compose -f {{ bahmni_mart_scdf_docker_compose_location }} up -d