
- name: Check if docker needs an update
  yum:
    list: docker-engine
  register: docker_info
  ignore_errors: true

- name: Uninstall docker
  yum:
    name: docker-engine
    state: absent
  when: docker_info.results|length != 0 and docker_info.results[0].version != "{{ docker_version }}"

- name: Install docker
  command: yum install -y http://get.docker.com/rpm/1.7.0/centos-6/RPMS/x86_64/docker-engine-1.7.0-1.el6.x86_64.rpm

- name: Evaluate docker compose url
  shell: "echo {{ docker_compose_url }}"
  register: evaluated_docker_compose_url

- name: Install docker-compose
  get_url:
    url: "{{ evaluated_docker_compose_url.stdout }}"
    dest: /usr/bin/docker-compose
    mode: 0755

- name: Start docker and enabled at boot
  service:
    name: docker
    enabled: yes
    state: started

