download_folder: /opt
postgres92_repo_rpm_name: pgdg-centos92-9.2-7.noarch.rpm
postgres96_repo_rpm_name: pgdg-redhat-repo-42.0-11.noarch.rpm
postgres92_repo_download_url: http://yum.postgresql.org/9.2/redhat/rhel-6-x86_64/{{postgres92_repo_rpm_name}}
postgres96_repo_download_url: https://yum.postgresql.org/9.6/redhat/rhel-6-x86_64/{{postgres96_repo_rpm_name}}
postgres92_repo_rpm_location: "{{download_folder}}/{{ postgres92_repo_rpm_name}}"
postgres96_repo_rpm_location: "{{download_folder}}/{{ postgres96_repo_rpm_name}}"
postgres92_version: 9.2
postgres96_version: 9.6
postgres92_bin_version: 92
postgres96_bin_version: 96
postgres_password: "{{ postgres_password }}"
postgresql_data_dir: /var/lib/pgsql
postgres_hba_configurations:
  # TYPE  DATABASE        USER            ADDRESS                 METHOD
  - 'local   all             all                                    md5'
  - 'host    all             all             0.0.0.0/0               md5'
  - 'host    all             all             ::0/0                   md5'
